rg_name                  = "aman-rg-g1112"
rg_location              = "australiacentral"
rg_name1                 = "aman-rg-g1113"
rg_location1             = "australiacentral"
account_replication_type = "LRS"
account_tier             = "Standard"
name                     = "ivansaaaaaa1123"
name1                    = "ivansaaaaaa112345"